name: Auto Format with Prettier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Prettier Auto Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Prettier and auto commit
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write "**/*.js"
          commit_message: "chore: auto-format with Prettier"
